### ISSUE TITLE
Create User Story

### ISSUE THREAD

**Issue by specsnstats** [Rallen4/project1-animal-crossing#1]
this

**Comment by charlottehulseman** [comment]
**User Stories**

- As an experienced gamer who favors social and life simulation games such as Animal Crossing, I'd like to be able to track my progress to maximize my success and evolution of my character.
- As a new and infrequent gamer, I'd like a video game guide to navigate the several different aspects and narratives within social and life simulation games and to remind me what to explore at different points in the game. 
- As the parent of a young gamer, I'd like to refer to a platform with details and information about the game so I can act as a guide or collaborator.
